### ISSUE TITLE
Retrieve SNB into separate process

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/ima-agent#10]
Currently Skale Network Browser (SNB) is a part of IMA agent codebase. We need to retrieve SNB into separate process that will be running separately in IMA agent container. Base requirements:
- Retrieve SNB into separate process
- Write a python script (or ts, @dmytrotkk to choose) to collect information about connected chains 
- Write this data into json file and make IMA agent read data from this file

**Comment by DmytroNazarenko** [comment]
ima-agent: 2.1.0-beta.2

**Comment by PolinaKiporenko** [comment]
https://github.com/skalenetwork/ima-agent/blob/develop/docs/SNB.md
