### ISSUE TITLE
Improve network off-line detection in IMA Agent

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/ima-agent#16]
Improve usage of `await rpcCall.checkUrl(...)` everywhere in IMA Agent.
This call is quick check for network connection problems and should be used wide as possible and correct,

**Comment by PolinaKiporenko** [comment]
https://github.com/skalenetwork/internal-support/issues/884

**Comment by sergiy-skalelabs** [comment]
Will be done automatically. Required built-in TypeScript validations will show us wrong-used `Promise`es.

**Comment by DmytroNazarenko** [comment]
ima-agent: 2.1.0-beta.2

**Comment by EvgeniyZZ** [comment]
Mark as resolved
New issue related: https://github.com/skalenetwork/ima-agent/issues/75
