### ISSUE TITLE
Rewrite IMA agent on Typescript

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/ima-agent#25]
It will allow us to use typed language and avoid a lot of problems with checking var types. Also the codebase will be cleaned from redundant code

**Comment by PolinaKiporenko** [comment]
For 2.3 release just change file extension with '.ts' and adding 'ANY' in types, in next releases will gradually migrate to Typescript

**Comment by DmytroNazarenko** [comment]
ima-agent: 2.1.0-beta.2
