### ISSUE TITLE
Improve asynchronous call handlers

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/ima-agent#3]
Asynchronous call handlers handlers in IMA Agent, such as JSON RPC class, often occupy lot of nested code space because of compound call handlers. This is especially visible with multiple nested asynchronous call handlers.
Make asynchronous call handlers split into call initiators and handler functions defined separately from each other and allow to read code of IMA Agent in a more plain manner.

**Comment by PolinaKiporenko** [comment]
ima- agent 2.1.0-beta.2
